# Site wide configuration

title: All Your Figure Are Belong To Us
description: "example() figures"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://yutannihilation.github.io
baseurl: /allYourFigureAreBelongToUs

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
highlighter: pygments
#markdown: redcarpet
kramdown:
  toc_levels: 1..2
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Hiroaki Yutani
  email:
  twitter: yutannihilation
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:
excerpt_separator: ""

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
